language: python

python:
    - "2.6"
    - "2.7"

install:
    - pip install -r etc/reqs-dev.txt

script:
    - nosetests -s

after_success:
    - pip install coveralls
    - coverage run --source=june setup.py -q nosetests
    - coveralls

notifications:
    email: false
